export const categories = [
  { id: 'music', label: 'Shastriya Sangeet', icon: '🎵', description: 'Classical Music', count: 24 },
  { id: 'dance', label: 'Nritya Kala', icon: '💃', description: 'Classical Dance', count: 18 },
  { id: 'yoga', label: 'Yoga & Dhyan', icon: '🧘', description: 'Yoga & Meditation', count: 31 },
  { id: 'art', label: 'Chitrakala', icon: '🎨', description: 'Traditional Art', count: 15 },
  { id: 'sanskrit', label: 'Sanskrit', icon: '📜', description: 'Ancient Language', count: 12 },
  { id: 'vedic', label: 'Vedic Studies', icon: '🕉️', description: 'Scriptures & Wisdom', count: 9 },
  { id: 'cooking', label: 'Paaka Vidya', icon: '🍛', description: 'Traditional Cooking', count: 22 },
  { id: 'craft', label: 'Hastkala', icon: '🏺', description: 'Traditional Crafts', count: 17 },
]

export const instructors = [
  {
    id: 'inst-1',
    name: 'Pandit Ravishankar Mishra',
    avatar: null,
    initials: 'PM',
    title: 'Hindustani Classical Music Maestro',
    bio: 'With over 40 years of experience in Hindustani classical music, Pandit Mishraji has trained under the legendary Ustad Bismillah Khan. He has performed at the prestigious Sawai Gandharva Bhimsen Festival and has taught over 2000 students globally.',
    courses: 8,
    students: 12500,
    rating: 4.9,
    category: 'music',
    verified: true,
    role: 'instructor',
  },
  {
    id: 'inst-2',
    name: 'Guru Meenakshi Sundaram',
    avatar: null,
    initials: 'MS',
    title: 'Bharatanatyam Exponent',
    bio: 'A disciple of Kalakshetra Foundation, Guru Meenakshi has dedicated 35 years to preserving and teaching Bharatanatyam. She has been conferred the Sangeet Natak Akademi Award for her contributions to classical dance.',
    courses: 6,
    students: 8900,
    rating: 4.8,
    category: 'dance',
    verified: true,
    role: 'instructor',
  },
  {
    id: 'inst-3',
    name: 'Swami Anandagiri',
    avatar: null,
    initials: 'SA',
    title: 'Yoga & Pranayama Master',
    bio: 'Trained at Rishikesh and Mysore, Swami Anandagiri brings the authentic traditions of Ashtanga Yoga and Pranayama to modern practitioners. His holistic approach blends ancient wisdom with contemporary wellness.',
    courses: 12,
    students: 28000,
    rating: 4.9,
    category: 'yoga',
    verified: true,
    role: 'instructor',
  },
  {
    id: 'inst-4',
    name: 'Seema Devi',
    avatar: null,
    initials: 'SD',
    title: 'Madhubani & Warli Art Expert',
    bio: 'A master artist from Mithila, Seema Devi has been practicing and teaching traditional Madhubani painting for 25 years. Her work has been exhibited in galleries across India, USA, and Japan.',
    courses: 5,
    students: 5600,
    rating: 4.7,
    category: 'art',
    verified: true,
    role: 'instructor',
  },
  {
    id: 'inst-5',
    name: 'Prof. Ramesh Shastri',
    avatar: null,
    initials: 'RS',
    title: 'Sanskrit Scholar & Vedic Educator',
    bio: 'A retired professor from Banaras Hindu University with a PhD in Sanskrit literature. Prof. Shastri has published 12 books on Sanskrit grammar and Vedic philosophy.',
    courses: 9,
    students: 7200,
    rating: 4.8,
    category: 'sanskrit',
    verified: true,
    role: 'instructor',
  },
  {
    id: 'inst-6',
    name: 'Chef Ananya Krishnamurthy',
    avatar: null,
    initials: 'AK',
    title: 'Traditional Indian Cuisine Expert',
    bio: 'A culinary historian and chef who has spent 20 years documenting and teaching regional Indian cuisines. Trained in South Indian, Bengali, Rajasthani, and Mughlai cooking traditions.',
    courses: 7,
    students: 15800,
    rating: 4.6,
    category: 'cooking',
    verified: true,
    role: 'instructor',
  },
]

export const courses = [
  {
    id: 'course-1',
    title: 'Hindustani Classical Vocal: From Raga to Performance',
    description: 'A comprehensive journey into the heart of Hindustani classical music. Learn the foundational ragas, tala systems, and develop your voice through systematic riyaz. This course covers Yaman, Bhairav, Bhimpalasi, and 12 other essential ragas with compositions in three lays.',
    shortDesc: 'Master the foundations of Hindustani classical music — ragas, talas & vocal techniques',
    instructor: instructors[0],
    category: 'music',
    categoryLabel: 'Shastriya Sangeet',
    thumbnail: null,
    thumbnailGradient: 'from-amber-900 via-red-900 to-amber-800',
    thumbnailEmoji: '🎵',
    price: 2999,
    originalPrice: 5999,
    rating: 4.9,
    reviewCount: 847,
    studentCount: 4280,
    duration: '48 hours',
    totalLessons: 96,
    level: 'Beginner to Intermediate',
    language: 'Hindi & English',
    lastUpdated: 'March 2024',
    featured: true,
    bestseller: true,
    tags: ['Raga', 'Taal', 'Bandish', 'Sur', 'Classical Vocal'],
    curriculum: [
      {
        section: 'Introduction to Hindustani Music',
        lessons: [
          { id: 'l1', title: 'What is Shastriya Sangeet?', duration: '18:30', free: true },
          { id: 'l2', title: 'History of Hindustani Music', duration: '24:15', free: true },
          { id: 'l3', title: 'Understanding Shruti and Swara', duration: '31:00', free: false },
          { id: 'l4', title: 'The Seven Svaras — Sa Re Ga Ma', duration: '28:45', free: false },
        ]
      },
      {
        section: 'Voice Cultivation & Riyaz',
        lessons: [
          { id: 'l5', title: 'Morning Riyaz Techniques', duration: '22:00', free: false },
          { id: 'l6', title: 'Breathing and Diaphragm Control', duration: '19:30', free: false },
          { id: 'l7', title: 'Sargam Practice — Aaroha & Avaroha', duration: '35:20', free: false },
          { id: 'l8', title: 'Alankaar Series — 15 Fundamental Alankars', duration: '42:10', free: false },
        ]
      },
      {
        section: 'Raga Yaman — The Evening Raga',
        lessons: [
          { id: 'l9', title: 'Introduction to Raga Yaman', duration: '26:00', free: false },
          { id: 'l10', title: 'Aaroha-Avaroha and Pakad of Yaman', duration: '33:15', free: false },
          { id: 'l11', title: 'Vilambit Bandish in Yaman', duration: '47:30', free: false },
          { id: 'l12', title: 'Drut Bandish in Yaman', duration: '39:00', free: false },
        ]
      },
    ],
    videoId: 'dQw4w9WgXcQ',
  },
  {
    id: 'course-2',
    title: 'Bharatanatyam Foundation: Adavus to Abhinaya',
    description: 'Learn the sacred classical dance of South India from the ground up. This course teaches the fundamental adavus, mudras, and expressions (abhinaya) that form the backbone of Bharatanatyam. Perfect for beginners with no prior dance experience.',
    shortDesc: 'Complete Bharatanatyam training — Adavus, Mudras, Abhinaya & solo pieces',
    instructor: instructors[1],
    category: 'dance',
    categoryLabel: 'Nritya Kala',
    thumbnail: null,
    thumbnailGradient: 'from-red-900 via-rose-900 to-pink-900',
    thumbnailEmoji: '💃',
    price: 3499,
    originalPrice: 6999,
    rating: 4.8,
    reviewCount: 623,
    studentCount: 3100,
    duration: '62 hours',
    totalLessons: 124,
    level: 'All Levels',
    language: 'Tamil, Hindi & English',
    lastUpdated: 'January 2024',
    featured: true,
    bestseller: false,
    tags: ['Adavus', 'Mudras', 'Abhinaya', 'Nattuvangam', 'Alarippu'],
    curriculum: [
      {
        section: 'Foundations of Bharatanatyam',
        lessons: [
          { id: 'l1', title: 'History and Origins of Bharatanatyam', duration: '20:00', free: true },
          { id: 'l2', title: 'Costume, Makeup and Jewellery', duration: '15:30', free: true },
          { id: 'l3', title: 'Aramandi — The Basic Stance', duration: '25:00', free: false },
          { id: 'l4', title: 'Tattu Adavu — 8 Variations', duration: '38:45', free: false },
        ]
      },
      {
        section: 'Hasta Mudras — Hand Gestures',
        lessons: [
          { id: 'l5', title: 'Asamyuta Hastas — 28 Single-Hand Mudras', duration: '55:00', free: false },
          { id: 'l6', title: 'Samyuta Hastas — 24 Combined Mudras', duration: '48:20', free: false },
          { id: 'l7', title: 'Navagraha and Dasha Avatara Mudras', duration: '33:10', free: false },
        ]
      },
    ],
    videoId: 'dQw4w9WgXcQ',
  },
  {
    id: 'course-3',
    title: 'Yoga Sadhana: Ashtanga, Pranayama & Dhyan',
    description: 'A holistic yoga course rooted in the ancient Ashtanga tradition of Patanjali. Learn asanas, pranayama techniques, meditation practices, and the philosophical underpinnings of yoga. Includes 30-day structured daily practice schedule.',
    shortDesc: 'Ancient yoga traditions — Asanas, Pranayama, Dhyan & Yogic philosophy',
    instructor: instructors[2],
    category: 'yoga',
    categoryLabel: 'Yoga & Dhyan',
    thumbnail: null,
    thumbnailGradient: 'from-green-900 via-emerald-900 to-teal-900',
    thumbnailEmoji: '🧘',
    price: 1999,
    originalPrice: 3999,
    rating: 4.9,
    reviewCount: 1842,
    studentCount: 12400,
    duration: '38 hours',
    totalLessons: 76,
    level: 'All Levels',
    language: 'Sanskrit, Hindi & English',
    lastUpdated: 'April 2024',
    featured: true,
    bestseller: true,
    tags: ['Asana', 'Pranayama', 'Dhyan', 'Ashtanga', 'Kundalini'],
    curriculum: [
      {
        section: 'Introduction to Yoga Philosophy',
        lessons: [
          { id: 'l1', title: 'Patanjali\'s Yoga Sutras Overview', duration: '22:00', free: true },
          { id: 'l2', title: 'The Eight Limbs of Yoga — Ashtanga', duration: '28:30', free: true },
          { id: 'l3', title: 'Yama and Niyama — Ethical Foundation', duration: '35:00', free: false },
        ]
      },
    ],
    videoId: 'dQw4w9WgXcQ',
  },
  {
    id: 'course-4',
    title: 'Madhubani Painting: Ancient Art of Mithila',
    description: 'Discover the vibrant folk art tradition of Madhubani — rooted in the Mithila region of Bihar. This course covers line drawing techniques, natural color preparation, and traditional motifs including fish, lotus, sun, moon, and mythological figures.',
    shortDesc: 'Traditional Mithila folk art — techniques, motifs & natural colors',
    instructor: instructors[3],
    category: 'art',
    categoryLabel: 'Chitrakala',
    thumbnail: null,
    thumbnailGradient: 'from-orange-900 via-amber-900 to-yellow-900',
    thumbnailEmoji: '🎨',
    price: 1499,
    originalPrice: 2999,
    rating: 4.7,
    reviewCount: 412,
    studentCount: 2800,
    duration: '28 hours',
    totalLessons: 56,
    level: 'Beginner',
    language: 'Maithili, Hindi & English',
    lastUpdated: 'February 2024',
    featured: false,
    bestseller: false,
    tags: ['Madhubani', 'Folk Art', 'Mithila', 'Traditional Painting'],
    curriculum: [
      {
        section: 'Introduction to Madhubani Art',
        lessons: [
          { id: 'l1', title: 'History & Geography of Mithila Art', duration: '16:00', free: true },
          { id: 'l2', title: 'Materials — Traditional vs Modern', duration: '12:30', free: true },
          { id: 'l3', title: 'Basic Lines and Patterns', duration: '24:00', free: false },
        ]
      },
    ],
    videoId: 'dQw4w9WgXcQ',
  },
  {
    id: 'course-5',
    title: 'Sanskrit Foundations: Devanagari to Conversational',
    description: 'A systematic approach to learning Sanskrit — starting from Devanagari script, moving through Panini\'s grammar, and building conversational ability. This course makes the language of the Vedas and Upanishads accessible to modern learners.',
    shortDesc: 'Learn Sanskrit from script to conversation — Devanagari, grammar & literature',
    instructor: instructors[4],
    category: 'sanskrit',
    categoryLabel: 'Sanskrit',
    thumbnail: null,
    thumbnailGradient: 'from-purple-900 via-violet-900 to-indigo-900',
    thumbnailEmoji: '📜',
    price: 2499,
    originalPrice: 4999,
    rating: 4.8,
    reviewCount: 328,
    studentCount: 1900,
    duration: '54 hours',
    totalLessons: 108,
    level: 'Beginner to Advanced',
    language: 'Sanskrit, Hindi & English',
    lastUpdated: 'December 2023',
    featured: false,
    bestseller: false,
    tags: ['Sanskrit', 'Devanagari', 'Panini', 'Grammar', 'Vedic'],
    curriculum: [
      {
        section: 'Devanagari Script Mastery',
        lessons: [
          { id: 'l1', title: 'Introduction to Sanskrit & Its Importance', duration: '18:00', free: true },
          { id: 'l2', title: 'Vowels (Svaras) — 16 Basic Vowels', duration: '26:30', free: true },
          { id: 'l3', title: 'Consonants (Vyanjanas) — Classification', duration: '32:00', free: false },
        ]
      },
    ],
    videoId: 'dQw4w9WgXcQ',
  },
  {
    id: 'course-6',
    title: 'Traditional Indian Cuisine: Regional Masterclass',
    description: 'A culinary journey through India\'s diverse regional cuisines. From the aromatic biryanis of Hyderabad to the tangy chutneys of Tamil Nadu, the rich curries of Punjab to the subtle flavors of Odia cooking — master authentic recipes and cooking techniques.',
    shortDesc: 'Authentic regional Indian cooking — 8 cuisines, 120+ recipes & culinary history',
    instructor: instructors[5],
    category: 'cooking',
    categoryLabel: 'Paaka Vidya',
    thumbnail: null,
    thumbnailGradient: 'from-red-900 via-orange-900 to-amber-900',
    thumbnailEmoji: '🍛',
    price: 1799,
    originalPrice: 3599,
    rating: 4.6,
    reviewCount: 956,
    studentCount: 7800,
    duration: '42 hours',
    totalLessons: 84,
    level: 'Beginner to Intermediate',
    language: 'Hindi & English',
    lastUpdated: 'May 2024',
    featured: true,
    bestseller: true,
    tags: ['Indian Cooking', 'Biryani', 'Spices', 'Regional Cuisine'],
    curriculum: [
      {
        section: 'The Philosophy of Indian Food',
        lessons: [
          { id: 'l1', title: 'Food as Medicine — Ayurvedic Perspective', duration: '20:00', free: true },
          { id: 'l2', title: 'The Six Tastes — Shad Rasa', duration: '16:30', free: true },
          { id: 'l3', title: 'Spice Mastery — 25 Essential Spices', duration: '38:00', free: false },
        ]
      },
    ],
    videoId: 'dQw4w9WgXcQ',
  },
  {
    id: 'course-7',
    title: 'Kathak: The Dance of Storytellers',
    description: 'Explore Kathak — the classical dance of North India — known for its intricate footwork, spins (chakkar), and expressive storytelling. This course covers Lucknow gharana style with tatkaar, chakkar, gat, and thumri compositions.',
    shortDesc: 'Lucknow gharana Kathak — footwork, spins, expressions & compositions',
    instructor: {
      id: 'inst-7',
      name: 'Pt. Birju Swarup',
      initials: 'BS',
      title: 'Kathak Exponent — Lucknow Gharana',
      rating: 4.9,
      students: 6200,
      courses: 4,
      verified: true,
    },
    category: 'dance',
    categoryLabel: 'Nritya Kala',
    thumbnail: null,
    thumbnailGradient: 'from-pink-900 via-rose-900 to-red-900',
    thumbnailEmoji: '🌀',
    price: 3299,
    originalPrice: 6599,
    rating: 4.9,
    reviewCount: 389,
    studentCount: 2100,
    duration: '58 hours',
    totalLessons: 116,
    level: 'All Levels',
    language: 'Hindi & English',
    lastUpdated: 'March 2024',
    featured: false,
    bestseller: false,
    tags: ['Kathak', 'Lucknow Gharana', 'Tatkaar', 'Chakkar', 'Thumri'],
    curriculum: [],
    videoId: 'dQw4w9WgXcQ',
  },
  {
    id: 'course-8',
    title: 'Vedic Chanting & Mantra Vidya',
    description: 'Learn the authentic pronunciation and chanting of Vedic mantras — from the Rigveda, Samaveda, and Atharvaveda. This course covers svaras (pitch accents), sandhi rules, and the profound meaning behind sacred mantras.',
    shortDesc: 'Authentic Vedic chanting — mantras, svaras, sandhi & their meanings',
    instructor: {
      id: 'inst-8',
      name: 'Pt. Shivkumar Pathak',
      initials: 'SP',
      title: 'Vedic Pandit & Mantra Vidya Expert',
      rating: 4.8,
      students: 4100,
      courses: 6,
      verified: true,
    },
    category: 'vedic',
    categoryLabel: 'Vedic Studies',
    thumbnail: null,
    thumbnailGradient: 'from-yellow-900 via-amber-900 to-orange-900',
    thumbnailEmoji: '🕉️',
    price: 1299,
    originalPrice: 2599,
    rating: 4.8,
    reviewCount: 267,
    studentCount: 1600,
    duration: '32 hours',
    totalLessons: 64,
    level: 'Beginner',
    language: 'Sanskrit & Hindi',
    lastUpdated: 'January 2024',
    featured: false,
    bestseller: false,
    tags: ['Vedic Mantras', 'Rigveda', 'Chanting', 'Upanishad', 'Svaras'],
    curriculum: [],
    videoId: 'dQw4w9WgXcQ',
  },
]

export const stats = [
  { label: 'Active Students', value: '85,000+', icon: '👥' },
  { label: 'Expert Instructors', value: '320+', icon: '🎓' },
  { label: 'Courses Available', value: '1,200+', icon: '📚' },
  { label: 'Languages', value: '24+', icon: '🌐' },
]

export const testimonials = [
  {
    id: 't1',
    name: 'Priya Sharma',
    location: 'Mumbai, Maharashtra',
    text: 'Ekam has truly transformed my understanding of classical music. Pandit Mishraji\'s teaching style is unparalleled — I can finally understand ragas in a way I never could from books alone.',
    course: 'Hindustani Classical Vocal',
    rating: 5,
    avatar: 'PS',
  },
  {
    id: 't2',
    name: 'Ankit Mehta',
    location: 'Bengaluru, Karnataka',
    text: 'The Bharatanatyam course is exceptional. Guru Meenakshi explains every mudra with such depth and cultural context. I\'ve been attending classes for 3 months and have learned more than 2 years of offline coaching.',
    course: 'Bharatanatyam Foundation',
    rating: 5,
    avatar: 'AM',
  },
  {
    id: 't3',
    name: 'Kavitha Reddy',
    location: 'Hyderabad, Telangana',
    text: 'Swami Anandagiri\'s yoga course is not just about asanas — it\'s a complete life transformation. The pranayama techniques have helped my anxiety tremendously. Truly grateful.',
    course: 'Yoga Sadhana',
    rating: 5,
    avatar: 'KR',
  },
]

export const mockUser = {
  id: 'user-1',
  name: 'Karan Singh',
  email: 'karan@example.com',
  role: 'instructor',
  avatar: null,
  initials: 'KS',
  joinedDate: 'January 2024',
  enrolledCourses: ['course-1', 'course-3'],
  myCourses: [],
}

export const adminStats = {
  totalCourses: 1247,
  totalStudents: 85420,
  totalInstructors: 324,
  pendingApprovals: 8,
  revenue: '₹42,80,000',
  monthlyGrowth: '+23%',
}
